const Announcement = require('../models/Announcement');

function values(body) {
  const text = (value) => (value || '').trim();
  const slug = text(body.slug) || text(body.title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  return { title: text(body.title), slug, description: text(body.description), type: text(body.type) || 'announcement', startDate: body.startDate || new Date(), active: body.active === 'on', featured: body.featured === 'on' };
}
function form(req, res, editing, announcement) { const formError = req.session.formError; delete req.session.formError; return res.render('admin/announcement-form', { title: `${editing ? 'Edit' : 'Add'} Announcement | MGM Admin`, page: 'announcements', announcement: announcement || { type: 'announcement', active: true }, editing, formError }); }
async function listAnnouncements(req, res, next) { try { const announcements = await Announcement.find().sort({ startDate: -1 }).lean(); return res.render('admin/announcements', { title: 'Announcements | MGM Admin', page: 'announcements', announcements }); } catch (error) { return next(error); } }
function createForm(req, res) { return form(req, res, false); }
async function editForm(req, res, next) { try { const announcement = await Announcement.findById(req.params.id).lean(); if (!announcement) return res.status(404).render('error', { message: 'Announcement not found.', error: {} }); return form(req, res, true, announcement); } catch (error) { return next(error); } }
async function create(req, res) { try { const data = values(req.body); data.image = req.file ? `/uploads/${req.file.filename}` : (req.body.imageUrl || '').trim(); const announcement = await Announcement.create(data); req.session.flash = { type: 'success', text: `${announcement.title} has been created.` }; return res.redirect('/admin/announcements'); } catch (error) { req.session.formError = error.code === 11000 ? 'That announcement URL slug is already in use.' : error.message; return res.redirect('/admin/announcements/create'); } }
async function update(req, res, next) { try { const announcement = await Announcement.findById(req.params.id); if (!announcement) throw new Error('Announcement not found.'); Object.assign(announcement, values(req.body)); if (req.file) announcement.image = `/uploads/${req.file.filename}`; else if ((req.body.imageUrl || '').trim()) announcement.image = req.body.imageUrl.trim(); await announcement.save(); req.session.flash = { type: 'success', text: 'Announcement updated.' }; return res.redirect('/admin/announcements'); } catch (error) { req.session.formError = error.code === 11000 ? 'That announcement URL slug is already in use.' : error.message; return res.redirect(`/admin/announcements/edit/${req.params.id}`); } }
async function remove(req, res, next) { try { const announcement = await Announcement.findByIdAndDelete(req.params.id); req.session.flash = { type: 'success', text: announcement ? 'Announcement deleted.' : 'Announcement already removed.' }; return res.redirect('/admin/announcements'); } catch (error) { return next(error); } }
async function toggle(req, res, next) { try { const announcement = await Announcement.findById(req.params.id); if (!announcement) throw new Error('Announcement not found.'); announcement.active = !announcement.active; await announcement.save(); req.session.flash = { type: 'success', text: `Announcement ${announcement.active ? 'published' : 'unpublished'}.` }; return res.redirect('/admin/announcements'); } catch (error) { return next(error); } }
module.exports = { listAnnouncements, createForm, editForm, create, update, remove, toggle };
