const Testimonial = require('../models/Testimonial');

function data(body) { return { name: (body.name || '').trim(), message: (body.message || '').trim(), date: body.date || new Date(), isActive: body.isActive === 'on' }; }
async function list(req, res, next) { try { const testimonials = await Testimonial.find().sort({ date: -1 }).lean(); return res.render('admin/testimonials', { title: 'Testimonials | MGM Admin', page: 'testimonials', testimonials }); } catch (error) { return next(error); } }
function createForm(req, res) { return res.render('admin/testimonial-form', { title: 'Add Testimonial | MGM Admin', page: 'testimonials', testimonial: { isActive: true }, editing: false, formError: req.session.formError }); }
async function editForm(req, res, next) { try { const testimonial = await Testimonial.findById(req.params.id).lean(); if (!testimonial) throw new Error('Testimonial not found.'); return res.render('admin/testimonial-form', { title: 'Edit Testimonial | MGM Admin', page: 'testimonials', testimonial, editing: true, formError: req.session.formError }); } catch (error) { return next(error); } }
async function create(req, res) { try { const testimonial = await Testimonial.create(Object.assign(data(req.body), { image: req.file ? `/uploads/${req.file.filename}` : (req.body.imageUrl || '').trim() })); req.session.flash = { type: 'success', text: `${testimonial.name}'s testimonial was added.` }; return res.redirect('/admin/testimonials'); } catch (error) { req.session.formError = error.message; return res.redirect('/admin/testimonials/create'); } }
async function update(req, res, next) { try { const testimonial = await Testimonial.findById(req.params.id); if (!testimonial) throw new Error('Testimonial not found.'); Object.assign(testimonial, data(req.body)); if (req.file) testimonial.image = `/uploads/${req.file.filename}`; else if ((req.body.imageUrl || '').trim()) testimonial.image = req.body.imageUrl.trim(); await testimonial.save(); req.session.flash = { type: 'success', text: 'Testimonial updated.' }; return res.redirect('/admin/testimonials'); } catch (error) { req.session.formError = error.message; return res.redirect(`/admin/testimonials/edit/${req.params.id}`); } }
async function remove(req, res, next) { try { await Testimonial.findByIdAndDelete(req.params.id); req.session.flash = { type: 'success', text: 'Testimonial deleted.' }; return res.redirect('/admin/testimonials'); } catch (error) { return next(error); } }
async function toggle(req, res, next) { try { const testimonial = await Testimonial.findById(req.params.id); testimonial.isActive = !testimonial.isActive; await testimonial.save(); req.session.flash = { type: 'success', text: `Testimonial ${testimonial.isActive ? 'published' : 'unpublished'}.` }; return res.redirect('/admin/testimonials'); } catch (error) { return next(error); } }
module.exports = { list, createForm, editForm, create, update, remove, toggle };
